@domain = https://localhost:4000

@AccessToken = {{loginToken.response.body.$.access_token}}

### 
# [Admin] 관리자 회원가입
POST {{domain}}/user
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123qweQWE!",
  "nickname": "어드민",
  "call": "010-1234-5678",
  "points": 0,
  "isAdmin": true
}

### 
# 사용자 회원가입
POST {{domain}}/user
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123qweQWE!",
  "nickname": "일반좁밥",
  "call": "010-5678-1234"
}

###
# [Admin] 관리자 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123qweQWE!"
}

###
# 사용자 로그인
# @name loginToken
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123qweQWE!"
}

###
# 사용자 정보 조회
GET {{domain}}/user/profile
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

### 
# 사용자 정보 업데이트
PATCH {{domain}}/user
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "currentPassword": "123qweQWE!",
  "newPassword": "123qweQWE!",
  "nickname": "오야지",
  "call": "010-1234-1234"
}

### 
# 사용자 삭제
DELETE {{domain}}/user
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

### 
# 로그아웃
POST {{domain}}/user/logout
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

### 
# 엑세스 토큰 재발급 (로그인 시간 연장)
# @name loginToken
POST {{domain}}/auth/refresh
Authorization: Bearer {{AccessToken}}



### 
# [Admin] 공연 생성 - imageURL
POST {{domain}}/performance
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "The Day After Tomorrow100",
  "description": "손이 시려워 꽁",
  "location": "감자국",
  "schedule": [
    { "date": "2023-12-29", "time": "05:00" },
    { "date": "2023-12-30", "time": "04:13" },
    { "date": "2023-12-31", "time": "05:00" }
  ],
  "price": 50000,
  "category": "영화",
  "imageUrl": "https://d3kxs6kpbh59hp.cloudfront.net/community/COMMUNITY/4ca213fc2f4f44bd89b82c4125dfddf7/73155ec1b0ee4bf5a310644f3e6a85f2_1649225815.png",
  "seatTemplateId": 1
}

###
# [Admin] 공연 생성 - imageFile
POST {{domain}}/performance
Authorization: Bearer {{AccessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

The Day After Tomorrow100
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

손이 시려워 꽁
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location"

감자국
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="schedule"

[{"date": "2023-12-29", "time": "05:00"}, {"date": "2023-12-30", "time": "04:13"}, {"date": "2023-12-31", "time": "05:00"}]
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

50000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

영화
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="seatTemplateId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 
# 공연 전체 조회
GET {{domain}}/performance
Content-Type: application/json

### 
# 공연 상세 조회
GET {{domain}}/performance/1
Content-Type: application/json

### 
# 공연 상세 조회 (예매 가능 유무)
GET {{domain}}/performance/detail/1
Content-Type: application/json

###
# 공연 검색
GET {{domain}}/performance/detailed/search?title=the&category=영화
Content-Type: application/json

### 
# 공연 정보 수정 - imageURL
PATCH {{domain}}/performance/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "The Day After Tomorrow100",
  "description": "손이 시려워 꽁",
  "location": "감자국1",
  "schedule": [
    { "date": "2024-01-01", "time": "09:30" },
    { "date": "2024-01-02", "time": "09:00" }
  ],
  "price": 50000,
  "category": "영화",
  "imageUrl": "https://d3kxs6kpbh59hp.cloudfront.net/community/COMMUNITY/4ca213fc2f4f44bd89b82c4125dfddf7/73155ec1b0ee4bf5a310644f3e6a85f2_1649225815.png",
  "seatTemplateId": 1
}

###
# [Admin] 공연 정보 수정 - imageFile
PATCH {{domain}}/performance/1
Authorization: Bearer {{AccessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

The Day After Tomorrow100
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

손이 시려워 꽁
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location"

감자국
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="schedule"

[{"date": "2024-01-30", "time": "05:00"}, {"date": "2023-12-30", "time": "04:13"}, {"date": "2023-12-31", "time": "05:00"}]
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

50000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

영화
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="seatTemplateId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 
# [Admin] 공연 정보 삭제
DELETE {{domain}}/performance/2
Authorization: Bearer {{AccessToken}}
Content-Type: application/json



### 
# [Admin] 좌석 템플릿 생성
POST {{domain}}/template
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Custom Template2",
  "configuration": [
    { "grade": "VIP", "seatCount": 1, "price": 10000 },
    { "grade": "VVIP", "seatCount": 1, "price": 15000 },
    { "grade": "VVVIP", "seatCount": 1, "price": 20000 },
    { "grade": "A", "seatCount": 1, "price": 5000 },
    { "grade": "B", "seatCount": 1, "price": 2500 },
    { "grade": "C", "seatCount": 1, "price": 2000 }
  ]
}

### 
# [Admin] 좌석 템플릿 전체 조회
GET {{domain}}/template
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

### 
# [Admin] 좌석 템플릿 상세 조회
GET {{domain}}/template/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

### 
# [Admin] 좌석 템플릿 수정
PATCH {{domain}}/template/2
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Custom Template1",
  "configuration": [
    { "grade": "VIP", "seatCount": 2, "price": 1000 },
    { "grade": "VVIP", "seatCount": 3, "price": 1500 },
    { "grade": "VVVIP", "seatCount": 4, "price": 2000 },
    { "grade": "A", "seatCount": 1, "price": 500 },
    { "grade": "B", "seatCount": 1, "price": 250 }
  ]
}

### 
# [Admin] 좌석 템플릿 삭제
DELETE {{domain}}/template/2
Authorization: Bearer {{AccessToken}}
Content-Type: application/json



### 
# [Admin] 특정 공연의 좌석을 템플릿 기반으로 생성
POST {{domain}}/seat/performance/1/template/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

### 
# [Admin] 특정 공연의 모든 좌석 조회
GET {{domain}}/seat/performance/1
Authorization: Bearer {{AccessToken}}

### 
# [Admin] 특정 좌석 상세 조회
GET {{domain}}/seat/1
Authorization: Bearer {{AccessToken}}

### 
# [Admin] 특정 좌석 수정
PATCH {{domain}}/seat/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "grade": "VIP",
  "price": 12000
}

### 
# [Admin] 특정 좌석 삭제
DELETE {{domain}}/seat/1
Authorization: Bearer {{AccessToken}}

### 
# [Admin] 특정 공연의 좌석을 템플릿 기반으로 업데이트
PATCH {{domain}}/seat/performance/1/template/1
Authorization: Bearer {{AccessToken}}

### 
# 특정 공연에 할당된 전체 좌석 삭제
DELETE {{domain}}/seat/performance/1
Authorization: Bearer {{AccessToken}}



### 
# 예약 생성
POST {{domain}}/booking
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "performanceId": 1,
  "date": "2024-01-30",
  "time": "05:00",
  "seatNumbers": [1, 2, 3]
}

### 
# 예약 전체 조회
GET {{domain}}/booking
Authorization: Bearer {{AccessToken}}

### 
# 예약 상세 조회
GET {{domain}}/booking/1
Authorization: Bearer {{AccessToken}}

### 
# 예약 취소
DELETE {{domain}}/booking/1
Authorization: Bearer {{AccessToken}}