@domain = https://localhost:4000

### 
# 회원가입
# 이 요청은 새로운 어드민 사용자를 등록합니다.
POST {{domain}}/users/register
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com",
  "password": "123qweQWE!",
  "nickname": "어드민",
  "points": 0,
  "isAdmin": true
}

### 
# 회원가입
# 이 요청은 새로운 일반 사용자를 등록합니다.
POST {{domain}}/users/register
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com",
  "password": "123qweQWE!",
  "nickname": "일반좁밥",
  "points": 1000000,
  "isAdmin": false
}

###
# 로그인
# 이 요청은 사용자 로그인을 처리합니다.
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com",
  "password": "123qweQWE!"
}

###
# 사용자 정보 조회
# 이 요청은 현재 로그인된 사용자의 정보를 조회합니다. (인증 토큰 필요)
GET {{domain}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhY2h5dWNoZXBlQGdtYWlsLmNvbSIsInN1YiI6MiwiaWF0IjoxNzAzNTI5MzUxLCJleHAiOjE3MDM1Mjk5NTF9.jK4SND6w2vZhibnSyRZXmDo3yAR-TTeYODb8Un3iyR8
# Content-Type: application/json

### 
# 엑세스 토큰 재발급
# 이 요청은 현재 로그인된 사용자의 엑세스 토큰이 유효한지 검증합니다. (인증 토큰 필요)
POST {{domain}}/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhY2h5dWNoZXBlQGdtYWlsLmNvbSIsInN1YiI6MiwiaWF0IjoxNzAzNTI5MzUxLCJleHAiOjE3MDM1Mjk5NTF9.jK4SND6w2vZhibnSyRZXmDo3yAR-TTeYODb8Un3iyR8
Content-Type: application/json

### 
# 사용자 정보 업데이트
# 이 요청은 사용자 정보를 업데이트합니다. (인증 토큰 필요)
PATCH {{domain}}/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhY2h5dWNoZXBlQGdtYWlsLmNvbSIsInN1YiI6MiwiaWF0IjoxNzAzNTI5MzUxLCJleHAiOjE3MDM1Mjk5NTF9.jK4SND6w2vZhibnSyRZXmDo3yAR-TTeYODb8Un3iyR8

{
  "currentPassword": "123qweQWE!",
  "newPassword": "123qweQWE!",
  "nickname": "파츄체페 업데이트1"
}

### 
# 사용자 삭제
# 이 요청은 현재 로그인된 사용자를 삭제합니다. (인증 토큰 필요)
DELETE {{domain}}/users/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhY2h5dWNoZXBlQGdtYWlsLmNvbSIsInN1YiI6MiwiaWF0IjoxNzAzNTI5MzUxLCJleHAiOjE3MDM1Mjk5NTF9.jK4SND6w2vZhibnSyRZXmDo3yAR-TTeYODb8Un3iyR8

### 
# 로그아웃
# 이 요청은 사용자 로그아웃을 처리합니다.
POST {{domain}}/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhY2h5dWNoZXBlQGdtYWlsLmNvbSIsInN1YiI6MiwiaWF0IjoxNzAzNTI5MzUxLCJleHAiOjE3MDM1Mjk5NTF9.jK4SND6w2vZhibnSyRZXmDo3yAR-TTeYODb8Un3iyR8





### 
# 인증번호 요청
# 이 요청은 이메일 인증번호를 요청합니다.
POST {{domain}}/request-verify
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com"
}

### 
# 인증번호 확인
# 이 요청은 이메일 인증번호를 확인합니다.
POST {{domain}}/validate-verify
Content-Type: application/json

{
  "email": "pachyuchepe@gmail.com",
  "verifyCode": "123456"
}